
linters:
  disable-all: true
  enable:
    - bodyclose
    - contextcheck
    - copyloopvar
    - cyclop
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings: 
  cyclop:
    max-complexity: 15
  gocritic:
    disabled-checks:
      - singleCaseSwitch
  gosec:
    excludes:
      - G115
      - G306

issues:
  exclude-rules:
    - path: "."
      linters:
        - typecheck

run:
  timeout: 10m
