# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  -
    id: tfsec
    main: ./cmd/tfsec
    binary: tfsec
    ldflags:
    - "-X github.com/tfsec/tfsec/version.Version=${TAG} -s -w -extldflags '-fno-PIC -static'"
    env:
      - CGO_ENABLED=0
      - GOFLAGS=-mod=vendor
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
  -
    id: tfsec-checkgen
    main: ./cmd/tfsec-checkgen
    binary: tfsec-checkgen
    ldflags:
    - "-X github.com/tfsec/tfsec/version.Version={{.VERSION}} -s -w -extldflags '-fno-PIC -static'"
    env:
      - CGO_ENABLED=0
      - GOFLAGS=-mod=vendor
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
checksum:
  ids:
  - tfsec
  - tfsec-checkgen
  name_template: '{{ .ProjectName }}_checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
