language: go
go:
- 1.15
services:
- docker
env:
  global:
  - secure: "R4BS8u2baA8HnawuHE0fFYk/wGtcctDKICb/bWR0MKTp4OJ1DiCakM1BrwtLit3amUtCg5SWnbi5rvIbclXV/iW2P+ujDs8/COxDT2pfDHshTS+2TQY2UTzisACT9hOCjv5IdudqIs/tPPWFbRdKtYY6IbNglFPDKABRYEgh8ujwi5azW6Le4je7I3NhH4e1H3ocM33XtvkkEWsMeu2cec885hsQMb877azbfH+W68r/HJJm3Nbqsd/wQs/085btDtqrqk59tfYVllhHi7ZG3pHevNHc8h3CBdLGiWpXP+a2apND9CMiK7z9puB4U/eK+A0N02EX4/pqJ14KqpenCIUoYQ3VGSX4xOlJ8kcAeW52UebKd61YAI1s/SE0fF8XP6brZGbRlISBaLWSVbMKGDrVCCUJMRmInFwXqQHnrVi+FTe39xiqqJ6VMZ0Wiz1r+biS/UTXjzikC20i/NmHAJuqqnPimIG61vzDx/ajYx22TRWW6Ug5RaFcI79aR1G6EkB2qRxrfpvnPOn9J/bxnO39i6WZXdNwwQ+iAeZiOUpR6//XwkYBhvdYUo50BfGtOT2XbuABPuHyftGSCH16lRgNiKaGLjZBBhHHAl4AqIQl8O3eGaiXjcIsPafwBahisSrl6P8MjDYbkZ8rGGUpzzofyQ06Z9Lsff/Dw9KOfW4="
  - secure: "Day8odEGnbjVNu14BR/BIdR6mtPFC1gHgilpiwY/PKLjtQ/oJoq0ezLgJ3y4/AfCrqnILJaG4Rf5lgjgl30HgVjvzfG2qjuiB81h474I0Q/B4yefShqj2S577JwetQxPjQgKhCe7wFgIPGiizfJ1fJDJzfvfiscJt7NF6/r/WJo7AppeUwhXcACifiS4IYO1caa8O4eV6L5hyeRaZXWguEyfeeULXXYmQ3kOFYBANgp89YXOMtHIQd4z5U4jmcsj9y611+XG93QB8yBJO0GYfM0jxUQ0FkmTbbs3yUDwJsQ0hpOMGGgu226XsL/36Y/84ShrsXrIQC5Dx+PkClgssrrhCC80/kuOhFczVKWyB9PcY8iY1Z5kwL8RC32qqmrVQbafAun2DLC92ipDWSZcNDj6a8JgKt6hYpNd2d65FdEXVZcIfwNkcSL9HhjkzCQazGEt3PebcWB4Wpyo1IvwOWB/pL5WCZoYt3FbBTPj536FXCHo0Z1ozrlWm9dvndSaNZMDWGrXmOac1oUiaBzt+P2iB8+p9XuoZ358sOxHYG6+3m8oaZ6NilXV7CqB7Vr7TF13rEsvy2WtcPKt18lPu5a5v9igdWBYKHafbsBrNAmLhFVssyrrx0CX4d45PhZYVhJJ/ClVk9ScuWNA+6h6MJfdv2OKuNoO/vsuUDGWC/k="
  - secure: "DsVZoOmqfnFPYlk8mSA2fESJ1qjz0wKV5SWWeW4a0kiL4m04jwVH4S7R2d70A9OBP8bsa9Tay1YmIbTJAI1miJzTD0cTnXG2ib4jzlC8J5smIexNqk5pX1Z8N01JPrckXZbW6s0fDbewT9LMdiY0nMHgSRf5VFcN3Xe2wk+SH8fJt/N3vRSlRXOG0JlaCNnFWAHB1bQaYemvLfqIz5rCf4PbQw5At6NHdoHy+aoWK0wqmK8471WRNsOhx5ggaicCccoMSlTslPhKlkXCRxLJBLWY1AoN2q7XwrI9Te2MAnvANVrdBNvMywFFZXkxJgcwK0BOefm15vx49JqtLisZ+wpI6DCjwmMGgiru20sgb7Ani51Xzy58+vrSsEJvb5+1SMttzbso8mpvUucAUtCkj0MSXAehn/SxSfN6BzA0gyBh+2/PbTvcM1hgyNj+W19YLaFR9I+P5OHMqQsi9ajsB53cTebMUIdax6lnLAV8aYwBou5ZID38zQBagJjmRH/nvXI/rEGGwxjUv6Vrpdweclw8uWDGWbr2eyBD1Zdc+la/F6POJeqsB01JmCycOpLk/B7dNR3CJWD1dYjjo1zIECVDJi8xNzEP+d+Lx6GXrPIHDZFcGFDfxLN2BJ5nREXrMVlk0a/+LdoxZFgEJv8/u/+amJp6yUygM724NA0j43M="
jobs:
  include:
  - stage: test
    name: Run tests
    script:
    - make test
  - stage: build
    if: tag IS NOT blank
    name: Build
    script:
    - make build
    - make image
    deploy:
      provider: releases
      skip_cleanup: true
      name: tfsec $TRAVIS_TAG
      file:
      - bin/darwin/tfsec-darwin-amd64
      - bin/linux/tfsec-linux-amd64
      - bin/windows/tfsec-windows-amd64.exe
      - bin/darwin/tfsec-checkgen-darwin-amd64
      - bin/linux/tfsec-checkgen-linux-amd64
      - bin/windows/tfsec-checkgen-windows-amd64.exe 
      api_key:
        secure: "gnFbED/JgihbV3zO6BgMj1YY7W+LsMHgVbamdMXcwwI4+9ouUa87D3vXIBpbAPUK7/aNmBeqDhXYX9grpy1gUAkmfPXhqH3zuOFnSiwoGFkZe0coRzZiqNU/pzxB4sZDihDLvk/E8btdNmNwSz6JkYvSbmGfN+b6M1N6Ico/kocV/XPYjfhGcArpngJ0CdbP656ixVo+s9ogwQUI3fNeelX0ppBjj1X8HZMMyLPuDvAsslWn0lb4rTqvpJitqcPaff8VRtnrQExNm5dVhEo03t+zYzPt+6EFhhx2K+dPpnWcDfl6yw7E+mKeN/LZIvGx+9pTQ3I3sclvtQ/COQ2WQn3z5wa5h9D/fsKBS/WxYMx8jWU/TcBeNpLDZhJcILwtYISKi9KfxY8Mr4FcHa+3Zl+uGZHWdbVgx8VR7SdDPi+H7QKcNrMJr7HAE/bHYNocE9qygWWpzGupznYX9RCNRhT51ebSlC497ZPugAkEdlax3yZcNf9CRXrCMLguJhoU3lOK8FyKt8Vvr/OTgbdJT7f440N5U3ETn4d+McZTIH0Gu71DfUAivixCVM2Ex6lvzcms1ZTwSsZMs888eI7mnStJoBS2vNo5AjR2jF0/FlCAjQRl9xUY+mCcRDrsQE2mFpqst4DvBhyYqzXrAiAzemcgtCVsmWpYkd9QrpBde04="
      on:
        repo: tfsec/tfsec
        tags: true
  - stage: docs
    if: branch = master
    name: Publish Docs
    script:
    - make publish-docs
  - stage: publish image
    name: Publish Docker image
    if: tag IS NOT blank
    before_script:
    - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
    script:
    - make image
    - make push-image
