language: go
go:
- 1.14
services:
- docker
env:
  global:
    - secure: "Z5uOG+pcrS/5p8B0Pi+2eYnAJvzey16cN6pJm1jp6DNl6YxekEFMPIznb4qK9LYmAAdxjPr0GLOqkkUygrm51OLrK/oCT4ygDNMXMq/2Pvndj8NVyy0drji38D/v6HqGrNyDKRYKbYFcOGzwwBQGe9IYtahfUuXVU5NhdNrbW5nWjdgvbywomovW6FuUVbFrPHJH9WHnmfIPMzBEvYzD5831V646vLyVGXzehLe6z2d4vuANhGNKH0ACl/8Epv+TdODnGLJR10jkN+QC2r8NhdbdeHPOpgqPduAKsyCyZCDJZvIQsqCeuvUFSY5nqKYzCc2RpVjWo6iia3jKTL94ov0blhn+c/ZSKSwa4rQncGT8f1XWkYa+Bfn4sw1XWVA7cI+Xt1s7Z6axuOULfhmmbIbRu66qlpmUJnYwGMrGVuOluR3yGn2z7VBjqkND/fPm8bLrjRfFicxg4OoWYf1B+HPrPQvSzoX/wx5o10PhlDlH28VWGHHZlGXYq5qdtlTUhptYq6SZWNnyxgNE8ublkPBzc8VqS4wczplUGP0XEooWQ+nUdtp8f+GMHJ9pFRdMpG/hMilIBWh+CdLstUDfnx2zis64a05Cy+xZDFHxahyFs0LhV1B3tLlozR+LDfN+Uae1ozXDwqoZHeaVtdxpTSASyB9DhAKSpzSljp0vQa4="
    - secure: "Qw1Px9YAQBVcGCe3uonIArbUOZ2LG0Ev//0iitNIBt/zT47Z335tVdIbmqXgvqrX8UN8zjLrqp9sJL0pXVgBXRI46JD+hkYrc/gqpfsfILEZL31z1pHibye1ce69XnalZhUnRUwMy97qdk7jKswIfkfHIXdjQEXUT4wFlR7KxEGdE7EjVWQpSU5JKlzvuQUYXCixDr9sNREd3FShCpkXX0/TTau5nwL8TzL4IePEE0Bb6BfqWhHhQBL9lCQRvqmQLy272QDgB2eEvkyfbsiFZG8+71V7q/N7pvVShWSQm0NCDtKxv8YiTJuvn0nx78QQ6imo8frzvU7+MZth8Lqk64SiqRcoGqv4/6SPMX8q8m28QysxuScUb0Vy+e4MSXGJo2rGYXAH8FzD1v50BYgg0Eeqcpwc/ve7uHclz+dJxoKh7ytxaah2qa8pv2s/QcdRY/M1dGdVtVAgLnk85Epg7ay4r9MY4oMRL6/cA7003lx3Rs8/49dvzgjjWBcZ+/WSfPZVkhNjD2nIAZBQLWV0s4827u3YhDH3PiqkQsrCtC+waz1PI0J/QHtPUfeegFr2g+ra5oD2lJ4oVHf342HkxH1YeIQeymWU0d9kuvGTqEe9daw9lFVSXND7MPspTKV4ceyi5T0ELAd0dofgan1nC3vTShljBXfT7HRkfWT32eo="
jobs:
  include:
    - stage: test
      name: Run tests
      script:
        - make test
    - stage: build
      name: Build
      script:
        - make build
        - make image
      deploy:
        provider: releases
        skip_cleanup: true
        name: "tfsec $TRAVIS_TAG"
        file:
          - bin/darwin/tfsec-darwin-amd64
          - bin/linux/tfsec-linux-amd64
          - bin/windows/tfsec-windows-amd64.exe
        api_key:
          secure: lSWOIa90AV0XRjgwJhu4j8cPZTOe4Hg5NQP2pYkfwV2jdNg5LT995UaaDy05X0PAcbtyXo63QKbqbhMTkOmLzrb0PX0t1MdKO22xwBYEZLTrQnjIuZFzgYwJaXDiXWaRpM4yBzxOLeuKPdowIk6rgqbhiRAe9fMU8AQde2wKriplpi4VdwlsHLvcONI8QxicTdPAY1JSeandtIBy8vnnQOHgF5ajS21cE1TNj867B++c1wpyemxwo6Z50KHONiG+UBQTqe45d4UXiTEroI8G4Yqcd28q5AGptJJOSrB9JR4zO8d1CrfI1ppHd2vbowNCxdzpL367aYtKxTAdfzFhf1lm79+69bQjkeQKY10edbPlfA+6OeN+AdkVib7XRk4bhoegwX1Y2cpk3iGe8WKnh6+JDclqk4VamcQCbDGSh2Y9FGFOCIji/rO2EjFCg2cmISRqYR42oWt+Szo7Z9V3eucEy3ErdKiTg+5yLQHKrNlhJz0rus1MIxw52K+8JfP+OiYmLh/OXfBvtxl5EaNnHE4Hv2sdvkolRi3RUW1pffn3nc4JQNJX4wOCoDXZzfLza0nLiMjwFCjBucjxHfrcZ7aDrLvroQJ03CbpcsIrYc2dT37mdKksZzYSAHP8k4So/0R6ItzxWf6jUy+RriCCzX/3a4pUe3fJLBRDAg9h7GU=
        on:
          repo: liamg/tfsec
          tags: true
    - stage: publish image
      name: Publish Docker image
      if: tag IS NOT blank
      before_script:
      - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
      script:
        - make image
        - make push-image
