FROM alpine:3.16.0

# install git
RUN apk add --no-cache git

# work somewhere where we can write
COPY tfsec /usr/bin/tfsec
RUN chmod a+x /usr/bin/tfsec

# use a non-privileged user
RUN adduser -D tfsec
USER tfsec

# as we are not specifying an entrypoint, this is the default executed command
# that you could override
CMD [ "tfsec", "--help" ]
