name: tfsec release

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: releasing tfsec
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v2
      with:
        stable: 'false'
        go-version: '1.17'
    - run: go version

    - name: Release
      uses: goreleaser/goreleaser-action@v2
      with:
       version: latest
       args: release --rm-dist
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
