name: CI 
on: 
 push: 
  branches: [ github-action ] 
 pull_request: 
  branches: [ github-action ] 

jobs: 
 build: 
  runs-on: ubuntu-latest 
  steps: 
  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it 
  - uses: actions/checkout@v2 

  - name: Set up Python 3.x 
    uses: actions/setup-python@v2 
    with: 
     # Semantic version range syntax or exact version of a Python version 
     python-version: '3.x' 
     # Optional - x64 or x86 architecture, defaults to x64   
     architecture: 'x64' 

  - name: Install skencli 
    run: pip3 install --upgrade skencli 

  - name: Run skencli 
    run: skencli
