name: typos

on:
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  build:
    name: Detect typos
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run typo checks
      run: make typos
